# Generated by Django 2.2.12 on 2023-12-02 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20231201_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('device_name', models.CharField(max_length=255)),
                ('device_location', models.CharField(max_length=255)),
                ('device_type', models.CharField(max_length=100)),
                ('device_status', models.CharField(choices=[('on', 'On'), ('off', 'Off')], max_length=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.CustomUser')),
            ],
        ),
    ]
