# Generated by Django 2.2.12 on 2023-12-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20231201_1346'),
        ('device', '0002_auto_20231202_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('user_id', 'device_id')},
        ),
    ]
