# Generated by Django 2.2.12 on 2023-12-02 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20231201_1346'),
        ('device', '0003_auto_20231202_0317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('user', 'device_id')},
        ),
    ]
