# Generated by Django 3.2.22 on 2023-12-05 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20231201_1346'),
        ('device', '0004_auto_20231202_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='user.customuser'),
        ),
    ]
