version: '3.8'  
  
services:  
  iot-mysql:  
    build:
      context: ./docker_mysql
      dockerfile: Dockerfile
    image: iotmysql:8.0  
    container_name: iot-mysql  
    environment:  
      MYSQL_ROOT_PASSWORD: zyz123456  
  
  iot-emqx:  
    build: 
      context: ./docker_emqx
      dockerfile: Dockerfile
    image: iotemqx:1.0 
    container_name: iot-emqx  
    ports:  
      - "1883:1883"  
      - "8083:8083"  
      - "8084:8084"  
      - "8883:8883"  
      - "18083:18083"  
  
  iot-backend:  
    build: 
      context: ./docker_backend/IotManager
      dockerfile: Dockerfile
    image: iotbackend:1.0  
    container_name: iot-backend   
    ports:  
      - "8000:8000"  
    depends_on:  
      - iot-mysql  
      - iot-emqx  
  
  iot-frontend:  
    build:
      context: ./docker_frontend/Iot-manager
      dockerfile: Dockerfile
    image: iotfrontend:1.0  
    container_name: iot-frontend  
    ports:  
      - "8080:80" 
    depends_on:  
      - iot-backend